version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - noctx
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
      - node_modules
formatters:
  enable:
    - goimports
    - gofumpt
    - gci
  settings:
    gofumpt:
      module-path: github.com/omegaatt36/ytea
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true
    goimports:
      local-prefixes:
        - github.com/omegaatt36/ytea
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/omegaatt36/ytea)
  exclusions:
    paths:
      - docs
      - third_party$
      - builtin$
      - examples$
      - node_modules
